SELECT ID
FROM PUBLIC.EMPLOYEES AS E
WHERE EXISTS
		(SELECT SCORE
			FROM PUBLIC.SCORES AS S
			WHERE E.ID = S.EMPLOYEE_ID
				AND (S.SCORE = 'E' OR S.SCORE = 'D'));


SELECT DISTINCT EMPLOYEE_ID
FROM PUBLIC.SCORES AS S
WHERE S.SCORE = 'E'
	OR S.SCORE = 'D';